module.exports = (sequelize, DataTypes) => {
  const MprHdfcCard = sequelize.define(
    "mpr_hdfc_card",
    {
      uid: {
        type: DataTypes.STRING(255),
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
      mecode: { type: DataTypes.STRING(255), allowNull: true },
      me_name: { type: DataTypes.STRING(255), allowNull: true },
      cardnbr: { type: DataTypes.STRING(255), allowNull: true },
      legal_name: { type: DataTypes.STRING(255), allowNull: true },
      chg_date: { type: DataTypes.DATE, allowNull: true },
      process_date: { type: DataTypes.DATE, allowNull: true },
      terminal_no: { type: DataTypes.STRING(255), allowNull: true },
      stall_no: { type: DataTypes.STRING(255), allowNull: true },
      grp_desc: { type: DataTypes.STRING(255), allowNull: true },
      app_code: { type: DataTypes.STRING(255), allowNull: true },
      pymt_cur_code: { type: DataTypes.STRING(255), allowNull: true },
      pymt_chgamnt: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_comm: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_percent: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_servtax: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_sbcess: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_kkcess: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_cgst: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_sgst: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_igst: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_utgst: { type: DataTypes.DOUBLE, allowNull: true },
      pymt_netamnt: { type: DataTypes.DOUBLE, allowNull: true },
      txncode: { type: DataTypes.STRING(255), allowNull: true },
      envn: { type: DataTypes.STRING(255), allowNull: true },
      bh_posmode: { type: DataTypes.STRING(255), allowNull: true },
      me_currac: { type: DataTypes.STRING(255), allowNull: true },
      bh_meicat_me_trcode: { type: DataTypes.STRING(255), allowNull: true },
      ubs_acc: { type: DataTypes.STRING(255), allowNull: true },
      bh_time: {
        type: DataTypes.TIME,
        allowNull: true,
      },
      auth_curr_code: { type: DataTypes.STRING(255), allowNull: true },
      auth_amount: { type: DataTypes.DOUBLE, allowNull: true },
      auth_comm: { type: DataTypes.DOUBLE, allowNull: true },
      auth_servtax: { type: DataTypes.DOUBLE, allowNull: true },
      auth_sbcess: { type: DataTypes.DOUBLE, allowNull: true },
      auth_kkcess: { type: DataTypes.DOUBLE, allowNull: true },
      auth_cgst: { type: DataTypes.DOUBLE, allowNull: true },
      auth_sgst: { type: DataTypes.DOUBLE, allowNull: true },
      auth_igst: { type: DataTypes.DOUBLE, allowNull: true },
      auth_utgst: { type: DataTypes.DOUBLE, allowNull: true },
      auth_netamnt: { type: DataTypes.DOUBLE, allowNull: true },
      bh_cashamnt: { type: DataTypes.DOUBLE, allowNull: true },
      debitcredit_type: { type: DataTypes.STRING(255), allowNull: true },
      inr_chgamnt: { type: DataTypes.DOUBLE, allowNull: true },
      inr_comm: { type: DataTypes.DOUBLE, allowNull: true },
      inr_servtax: { type: DataTypes.DOUBLE, allowNull: true },
      inr_sbcess: { type: DataTypes.DOUBLE, allowNull: true },
      inr_kkcess: { type: DataTypes.DOUBLE, allowNull: true },
      inr_cgst: { type: DataTypes.DOUBLE, allowNull: true },
      inr_sgst: { type: DataTypes.DOUBLE, allowNull: true },
      inr_igst: { type: DataTypes.DOUBLE, allowNull: true },
      inr_utgst: { type: DataTypes.DOUBLE, allowNull: true },
      inr_netamnt: { type: DataTypes.DOUBLE, allowNull: true },
      gst_invoice: { type: DataTypes.STRING(255), allowNull: true },
      gst_transaction_id: { type: DataTypes.STRING(255), allowNull: true },
    },
    {
      tableName: "mpr_hdfc_card",
      timestamps: false,
    }
  );
  return MprHdfcCard;
};
