const { DataTypes } = require("sequelize");

module.exports = (sequelize) => {
  const PizzahutOrders = sequelize.define(
    "pizzahut_orders",
    {
      uid: {
        type: DataTypes.STRING(255),
        primaryKey: true,
      },
      timestamp: DataTypes.DATE,
      store_no: DataTypes.STRING(50),
      pos_terminal_no: DataTypes.STRING(50),
      transaction_no: DataTypes.STRING(50),
      date: DataTypes.DATEONLY,
      transaction_type: DataTypes.STRING(50),
      receipt_no: DataTypes.STRING(50),
      vat_bus_posting_group: DataTypes.STRING(50),
      created_on_pos_terminal: DataTypes.STRING(50),
      staff_id: DataTypes.STRING(50),
      original_date: DataTypes.DATEONLY,
      time: DataTypes.TIME,
      shift_no: DataTypes.STRING(50),
      shift_date: DataTypes.DATEONLY,
      wrong_shift: DataTypes.BOOLEAN,
      infocode_disc_group: DataTypes.STRING(50),
      customer_no: DataTypes.STRING(50),
      transaction_code: DataTypes.STRING(50),
      trans_sale_pmt_diff: DataTypes.DECIMAL(10, 2),
      net_amount: DataTypes.DECIMAL(10, 2),
      cost_amount: DataTypes.DECIMAL(10, 2),
      gross_amount: DataTypes.DECIMAL(10, 2),
      payment: DataTypes.DECIMAL(10, 2),
      discount_amount: DataTypes.DECIMAL(10, 2),
      customer_discount: DataTypes.DECIMAL(10, 2),
      total_discount: DataTypes.DECIMAL(10, 2),
      no_of_items: DataTypes.INTEGER,
      amount_to_account: DataTypes.DECIMAL(10, 2),
      rounded: DataTypes.DECIMAL(10, 2),
      customer_disc_group: DataTypes.STRING(50),
      entry_status: DataTypes.STRING(50),
      no_of_invoices: DataTypes.INTEGER,
      no_of_item_lines: DataTypes.INTEGER,
      statement_code: DataTypes.STRING(50),
      statement_no_not_used: DataTypes.STRING(50),
      refund_receipt_no: DataTypes.STRING(50),
      income_exp_amount: DataTypes.DECIMAL(10, 2),
      to_account: DataTypes.STRING(50),
      no_of_payment_lines: DataTypes.INTEGER,
      sale_is_return_sale: DataTypes.BOOLEAN,
      counter: DataTypes.STRING(50),
      time_when_total_pressed: DataTypes.TIME,
      time_when_trans_closed: DataTypes.TIME,
      trans_currency: DataTypes.STRING(10),
      items_posted: DataTypes.BOOLEAN,
      post_as_shipment: DataTypes.BOOLEAN,
      safe_entry_no: DataTypes.STRING(50),
      safe_code: DataTypes.STRING(50),
      manager_id: DataTypes.STRING(50),
      table_no: DataTypes.STRING(50),
      no_of_covers: DataTypes.INTEGER,
      split_number: DataTypes.STRING(50),
      table_description: DataTypes.STRING(255),
      sell_to_contact_no: DataTypes.STRING(50),
      gift_registration_no: DataTypes.STRING(50),
      member_card_no: DataTypes.STRING(50),
      sales_type: DataTypes.STRING(50),
      starting_point_balance: DataTypes.DECIMAL(10, 2),
      contains_forecourt_items: DataTypes.BOOLEAN,
      apply_to_doc_no: DataTypes.STRING(50),
      source_type: DataTypes.STRING(50),
      open_drawer: DataTypes.BOOLEAN,
      replicatedreplication: DataTypes.STRING(50),
      counter1: DataTypes.STRING(50),
      retrieved_from: DataTypes.STRING(50),
      receipt_no_2: DataTypes.STRING(50),
      z_report_id: DataTypes.STRING(50),
      y_report_id: DataTypes.STRING(50),
      delivered: DataTypes.STRING(100),
      comment: DataTypes.TEXT,
      duplicate: DataTypes.BOOLEAN,
      no_of_covers_aib: DataTypes.STRING(25),
      staff_name: DataTypes.STRING(100),
      permission_group: DataTypes.STRING(50),
      pos_receipt_no: DataTypes.STRING(50),
      pre_receipt_counter: DataTypes.STRING(50),
      server_id: DataTypes.STRING(50),
      server_name: DataTypes.STRING(100),
      managar_id: DataTypes.STRING(50),
      managar_name: DataTypes.STRING(100),
      token_no: DataTypes.STRING(50),
      yum_week: DataTypes.STRING(20),
      yum_year: DataTypes.STRING(10),
      return_manager_id: DataTypes.STRING(50),
      return_manager_name: DataTypes.STRING(100),
      pos_order_no: DataTypes.STRING(50),
      bill_print_status: DataTypes.STRING(50),
      last_printing_date: DataTypes.DATEONLY,
      last_printing_time: DataTypes.TIME,
      merge_table_no: DataTypes.STRING(50),
      merge_table_name: DataTypes.STRING(100),
      table_name: DataTypes.STRING(100),
      passengername: DataTypes.STRING(100),
      airline: DataTypes.STRING(50),
      flightno: DataTypes.STRING(50),
      seatno: DataTypes.STRING(20),
      source: DataTypes.STRING(100),
      destination: DataTypes.STRING(100),
      passportno: DataTypes.STRING(50),
      mial_file_generated: DataTypes.STRING(20),
      replication_counter: DataTypes.INTEGER,
      processed_for_sap: DataTypes.BOOLEAN,
      sap_counter: DataTypes.STRING(50),
      coupon_no: DataTypes.STRING(50),
      web_order_no: DataTypes.STRING(50),
      web_order: DataTypes.BOOLEAN,
      online_payment_received: DataTypes.BOOLEAN,
      online_payment_amount: DataTypes.DECIMAL(10, 2),
      old_version: DataTypes.STRING(50),
      paytm_counter: DataTypes.STRING(50),
      kautilya_bi_order_no: DataTypes.STRING(50),
      tax_liable: DataTypes.BOOLEAN,
      tax_area_code: DataTypes.STRING(20),
      state_in: DataTypes.STRING(50),
      tax_group_code: DataTypes.STRING(50),
      service_tax_registration_no: DataTypes.STRING(100),
      service_tax_amount: DataTypes.DECIMAL(10, 2),
      service_tax_entry: DataTypes.STRING(50),
      service_tax_cess_amount: DataTypes.DECIMAL(10, 2),
      service_tax_she_cess_amount: DataTypes.DECIMAL(10, 2),
      kot_no: DataTypes.STRING(50),
      pan_number: DataTypes.STRING(50),
      table_token_no: DataTypes.STRING(50),
      zomato_online_discount: DataTypes.DECIMAL(10, 2),
      zomato_online_discount_amt: DataTypes.DECIMAL(10, 2),
      instance_id: DataTypes.STRING(50),
      void_online: DataTypes.BOOLEAN,
      void_date: DataTypes.DATEONLY,
      online_void_time: DataTypes.TIME,
      online_order_taker: DataTypes.STRING(100),
      remove_service_charge: DataTypes.BOOLEAN,
      udio_payment: DataTypes.STRING(50),
      udio_payment_received: DataTypes.DECIMAL(10, 2),
      updated: DataTypes.DATE,
      magic_pin_order: DataTypes.STRING(50),
      zomato_visitor_id: DataTypes.STRING(100),
      order_received_time: DataTypes.DATE,
      dispatch_time: DataTypes.DATE,
      deliver_time: DataTypes.DATE,
      food_ready: DataTypes.DATE,
      sent_qr_code: DataTypes.STRING(10),
      load_time: DataTypes.DATE,
      cancel_order_reason: DataTypes.TEXT,
    },
    {
      tableName: "pizzahut_orders",
      timestamps: false,
    }
  );
  return PizzahutOrders;
};
