const THREE_PO_VS_POS_REASONS = {
  pos_vs_zomato_net_amount_delta: "NET_AMOUNT_ZOMATO_POS_MISMATCH",
  zomato_vs_pos_net_amount_delta: "NET_AMOUNT_ZOMATO_POS_MISMATCH",
  pos_vs_zomato_tax_paid_by_customer_delta:
    "TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH",
  zomato_vs_pos_tax_paid_by_customer_delta:
    "TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH",
  pos_vs_zomato_commission_value_delta: "COMMISSION_VALUE_ZOMATO_POS_MISMATCH",
  zomato_vs_pos_commission_value_delta: "COMMISSION_VALUE_ZOMATO_POS_MISMATCH",
  pos_vs_zomato_pg_applied_on_delta: "PG_APPLIED_ON_ZOMATO_POS_MISMATCH",
  zomato_vs_pos_pg_applied_on_delta: "PG_APPLIED_ON_ZOMATO_POS_MISMATCH",
  pos_vs_zomato_pg_charge_delta: "PG_CHARGE_ZOMATO_POS_MISMATCH",
  zomato_vs_pos_pg_charge_delta: "PG_CHARGE_ZOMATO_POS_MISMATCH",
  pos_vs_zomato_taxes_zomato_fee_delta: "TAXES_ZOMATO_FEE_ZOMATO_POS_MISMATCH",
  zomato_vs_pos_taxes_zomato_fee_delta: "TAXES_ZOMATO_FEE_ZOMATO_POS_MISMATCH",
  pos_vs_zomato_tds_amount_delta: "TDS_AMOUNT_ZOMATO_POS_MISMATCH",
  zomato_vs_pos_tds_amount_delta: "TDS_AMOUNT_ZOMATO_POS_MISMATCH",
  pos_vs_zomato_final_amount_delta: "FINAL_AMOUNT_ZOMATO_POS_MISMATCH",
  zomato_vs_pos_final_amount_delta: "FINAL_AMOUNT_ZOMATO_POS_MISMATCH",
  calculated_zomato_net_amount: "NET_AMOUNT_ZOMATO_SELF_MISMATCH",
  calculated_zomato_tax_paid_by_customer:
    "TAX_PAID_BY_CUSTOMER_ZOMATO_SELF_MISMATCH",
  calculated_zomato_commission_value: "COMMISSION_VALUE_ZOMATO_SELF_MISMATCH",
  calculated_zomato_pg_applied_on: "PG_APPLIED_ON_ZOMATO_SELF_MISMATCH",
  calculated_zomato_pg_charge: "PG_CHARGE_ZOMATO_SELF_MISMATCH",
  calculated_zomato_taxes_zomato_fee: "TAXES_ZOMATO_FEE_ZOMATO_SELF_MISMATCH",
  calculated_zomato_tds_amount: "TDS_AMOUNT_ZOMATO_SELF_MISMATCH",
  calculated_zomato_final_amount: "FINAL_AMOUNT_ZOMATO_SELF_MISMATCH",
};

const THREE_PO_VS_POS_REASON_LIST = [
  // Single errors
  "NET_AMOUNT_ZOMATO_POS_MISMATCH",
  "TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH",
  "COMMISSION_VALUE_ZOMATO_POS_MISMATCH",
  "PG_CHARGE_ZOMATO_POS_MISMATCH",

  // Combinations of 2
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH",
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH",
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH",
  "TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH",
  "TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH",
  "COMMISSION_VALUE_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH",

  // Combinations of 3
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH",
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH",
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH",
  "TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH",

  // Combination of all 4
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH",

  // Other existing reasons
  "PG_APPLIED_ON_ZOMATO_POS_MISMATCH",
  "TAXES_ZOMATO_FEE_ZOMATO_POS_MISMATCH",
  "TDS_AMOUNT_ZOMATO_POS_MISMATCH",
  "FINAL_AMOUNT_ZOMATO_POS_MISMATCH",
];

const THREE_PO_SELF_MISMATCH_REASON_LIST = [
  "NET_AMOUNT_ZOMATO_SELF_MISMATCH",
  "TAX_PAID_BY_CUSTOMER_ZOMATO_SELF_MISMATCH",
  "COMMISSION_VALUE_ZOMATO_SELF_MISMATCH",
  "PG_APPLIED_ON_ZOMATO_SELF_MISMATCH",
  "PG_CHARGE_ZOMATO_SELF_MISMATCH",
  "TAXES_ZOMATO_FEE_ZOMATO_SELF_MISMATCH",
  "TDS_AMOUNT_ZOMATO_SELF_MISMATCH",
  "FINAL_AMOUNT_ZOMATO_SELF_MISMATCH",
];

const THREEPO_EXCEL_MISMATCH_REASONS = {
  // Single errors
  NET_AMOUNT_ZOMATO_POS_MISMATCH: "Net Amount mismatch",
  TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH: "Tax Paid by Customer mismatch",
  COMMISSION_VALUE_ZOMATO_POS_MISMATCH: "Commission Value mismatch",
  PG_CHARGE_ZOMATO_POS_MISMATCH: "PG Charge mismatch",

  // Combinations of 2
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH":
    "Net Amount & Tax Paid by Customer mismatch",
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH":
    "Net Amount & Commission Value mismatch",
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH":
    "Net Amount & PG Charge mismatch",
  "TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH":
    "Tax Paid by Customer & Commission Value mismatch",
  "TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH":
    "Tax Paid by Customer & PG Charge mismatch",
  "COMMISSION_VALUE_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH":
    "Commission Value & PG Charge mismatch",

  // Combinations of 3
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH":
    "Net Amount, Tax Paid by Customer & Commission Value mismatch",
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH":
    "Net Amount, Tax Paid by Customer & PG Charge mismatch",
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH":
    "Net Amount, Commission Value & PG Charge mismatch",
  "TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH":
    "Tax Paid by Customer, Commission Value & PG Charge mismatch",

  // Combination of all 4
  "NET_AMOUNT_ZOMATO_POS_MISMATCH,TAX_PAID_BY_CUSTOMER_ZOMATO_POS_MISMATCH,COMMISSION_VALUE_ZOMATO_POS_MISMATCH,PG_CHARGE_ZOMATO_POS_MISMATCH":
    "Net Amount, Tax Paid by Customer, Commission Value & PG Charge mismatch",

  // Other existing reasons
  PG_APPLIED_ON_ZOMATO_POS_MISMATCH: "PG Applied On mismatch",
  TAXES_ZOMATO_FEE_ZOMATO_POS_MISMATCH: "Taxes Zomato Fee mismatch",
  TDS_AMOUNT_ZOMATO_POS_MISMATCH: "TDS Amount mismatch",
  FINAL_AMOUNT_ZOMATO_POS_MISMATCH: "Final Amount mismatch",

  // Self mismatch reasons
  NET_AMOUNT_ZOMATO_SELF_MISMATCH: "Net Amount self mismatch",
  TAX_PAID_BY_CUSTOMER_ZOMATO_SELF_MISMATCH:
    "Tax Paid by Customer self mismatch",
  COMMISSION_VALUE_ZOMATO_SELF_MISMATCH: "Commission Value self mismatch",
  PG_APPLIED_ON_ZOMATO_SELF_MISMATCH: "PG Applied On self mismatch",
  PG_CHARGE_ZOMATO_SELF_MISMATCH: "PG Charge self mismatch",
  TAXES_ZOMATO_FEE_ZOMATO_SELF_MISMATCH: "Taxes Zomato Fee self mismatch",
  TDS_AMOUNT_ZOMATO_SELF_MISMATCH: "TDS Amount self mismatch",
  FINAL_AMOUNT_ZOMATO_SELF_MISMATCH: "Final Amount self mismatch",
};

const CALCULATED_3PO_MISMATCH_SHEETS = [
  "ZOM_NET_AMO_MIS",
  "ZOM_TAX_PAI_BY_CUS_MIS",
  "ZOM_COM_VAL_MIS",
  "ZOM_PG_APP_ON_MIS",
  "ZOM_PG_CHA_MIS",
  "ZOM_TAX_ZOM_FEE_MIS",
  "ZOM_TDS_AMO_MIS",
  "ZOM_FIN_AMO_MIS",
];

module.exports = {
  THREE_PO_VS_POS_REASONS,
  THREE_PO_VS_POS_REASON_LIST,
  THREEPO_EXCEL_MISMATCH_REASONS,
  THREE_PO_SELF_MISMATCH_REASON_LIST,
  CALCULATED_3PO_MISMATCH_SHEETS,
};
